#!/usr/bin/env python3
"""Build a fully in-browser Hugging Face Space: Pyodide, no server, no framework.

Why not a normal Gradio Space
-----------------------------
Server-backed Gradio Spaces now require a paid plan. Static Spaces are free — and
for this project static is not a compromise, it is the honest deployment: the
Python runs in the visitor's browser, so a glossary of colleagues' names never
reaches Hugging Face's servers at all. "Nothing leaves your machine" stops being
a claim about how you deploy it and becomes a property of the page.

Why not gradio-lite
-------------------
Measured, not assumed: `@gradio/lite` 5.45 mounts but never starts Pyodide on an
HF static Space, because the page is not cross-origin isolated
(`SharedArrayBuffer` is undefined). The documented minimal example fails there
too, so this is not a markup problem. Plain Pyodide has no such requirement and
loads fine, so this builder drives Pyodide directly and renders the UI by hand.

That turns out better anyway: no framework bundle, a much faster first paint, and
the evidence panel is generated by :mod:`mondegreen.report` — the same code the
server-backed `app.py` uses, so the two frontends cannot drift.

The correction path has exactly one third-party dependency, numpy, which Pyodide
ships. `fugashi` is a C extension and is not available in the browser, so this
build falls back to the bundled 4,030-kanji reading table; the page says so
plainly, because without part-of-speech information the common-word protection
cannot fire and the damage rate is higher.

    python scripts/build_static_space.py --out hf/static_space
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from mondegreen import __version__
from mondegreen.report import CSS, EXAMPLE_GLOSSARY, EXAMPLE_TRANSCRIPT

#: Exactly the modules the correction path imports. Verified by walking the
#: import graph; training, benchmarking and runtime modules are absent.
PACKAGE_MODULES = (
    "__init__", "types", "phonetics", "reading", "glossary", "index",
    "gate", "hallucination", "corrector", "baselines", "report",
)
PYODIDE = "https://cdn.jsdelivr.net/pyodide/v0.28.3/full/"


def collect_files() -> dict:
    """Gather every file the browser filesystem needs, path -> text.

    Claim: SUPPORT.
    """
    files = {}
    for mod in PACKAGE_MODULES:
        path = os.path.join(REPO_ROOT, "mondegreen", f"{mod}.py")
        files[f"mondegreen/{mod}.py"] = open(path, encoding="utf-8").read()
    for name in ("kanji_readings.json", "common_kanji.json"):
        path = os.path.join(REPO_ROOT, "mondegreen", "data", name)
        files[f"mondegreen/data/{name}"] = open(path, encoding="utf-8").read()
    gate = os.path.join(REPO_ROOT, "models", "gate.json")
    if os.path.exists(gate):
        files["models/gate.json"] = open(gate, encoding="utf-8").read()
    return files


def build(out_dir: str) -> str:
    """Emit a single self-contained ``index.html``.

    Claim: LOCAL-SPEED -- the strongest available form of the claim: the code
    runs on the reader's machine, not on ours.
    """
    os.makedirs(out_dir, exist_ok=True)
    files = collect_files()
    payload = base64.b64encode(
        json.dumps(files, ensure_ascii=False).encode("utf-8")
    ).decode("ascii")

    html_doc = _PAGE.replace("__PAYLOAD__", payload)
    html_doc = html_doc.replace("__SHARED_CSS__", CSS)
    html_doc = html_doc.replace("__PYODIDE__", PYODIDE)
    html_doc = html_doc.replace("__VERSION__", __version__)
    html_doc = html_doc.replace("__EXAMPLE_TRANSCRIPT__", EXAMPLE_TRANSCRIPT)
    html_doc = html_doc.replace("__EXAMPLE_GLOSSARY__", EXAMPLE_GLOSSARY)

    out = os.path.join(out_dir, "index.html")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(html_doc)
    return out


_PAGE = r"""<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Mondegreen — 用語集を音韻的な硬い制約に変換するローカルASR訂正器</title>
<style>
:root{--bg:#fff;--fg:#202124;--muted:#5f6368;--line:#dadce0;--accent:#1a73e8;--soft:#f8f9fa}
*{box-sizing:border-box}
html,body{margin:0;padding:0;background:var(--bg);color:var(--fg);
  font-family:ui-sans-serif,system-ui,-apple-system,"Hiragino Sans","Noto Sans JP",sans-serif;
  line-height:1.65;-webkit-font-smoothing:antialiased}
.wrap{max-width:1120px;margin:0 auto;padding:22px 20px 60px}
h1{font-size:23px;margin:0 0 2px;letter-spacing:-.01em}
.tag{color:var(--muted);font-size:13.5px;margin:0 0 14px}
.privacy{background:#e6f4ea;border-left:3px solid #0d652d;padding:10px 14px;
  border-radius:0 6px 6px 0;font-size:13px;margin:0 0 16px}
.privacy b{color:#0d652d}
.warn{background:#fef7e0;border-left:3px solid #f9ab00;padding:9px 14px;
  border-radius:0 6px 6px 0;font-size:12.5px;margin:0 0 16px;color:#3c4043}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}
@media(max-width:860px){.grid{grid-template-columns:1fr}}
label{display:block;font-size:12.5px;font-weight:600;margin:0 0 5px;color:#3c4043}
textarea{width:100%;min-height:150px;padding:10px 12px;border:1px solid var(--line);
  border-radius:8px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;
  font-size:13px;line-height:1.75;resize:vertical;background:var(--bg);color:var(--fg)}
textarea:focus{outline:2px solid var(--accent);outline-offset:-1px;border-color:transparent}
.controls{display:flex;flex-wrap:wrap;gap:18px;align-items:center;margin:14px 0}
.ctl{display:flex;flex-direction:column;gap:2px;min-width:230px}
.ctl .row{display:flex;justify-content:space-between;font-size:12px;color:var(--muted)}
input[type=range]{width:100%;accent-color:var(--accent)}
.chk{display:flex;align-items:center;gap:6px;font-size:13px;color:#3c4043}
button{background:var(--accent);color:#fff;border:0;border-radius:8px;
  padding:10px 22px;font-size:14px;font-weight:600;cursor:pointer}
button:disabled{background:#c6c9cc;cursor:not-allowed}
button:hover:not(:disabled){background:#1765cc}
.tabs{display:flex;gap:2px;border-bottom:1px solid var(--line);margin:20px 0 0}
.tab{padding:8px 16px;font-size:13px;cursor:pointer;border:0;background:none;
  color:var(--muted);border-bottom:2px solid transparent;font-weight:600}
.tab.active{color:var(--accent);border-bottom-color:var(--accent)}
.panel{display:none;padding:16px 2px}
.panel.active{display:block}
pre{background:var(--soft);border:1px solid var(--line);border-radius:8px;
  padding:12px 14px;overflow-x:auto;font-size:12.5px;line-height:1.6;margin:0}
.status{font-size:13px;color:var(--muted);min-height:20px;margin:8px 0 0}
.bar{height:4px;background:#e8eaed;border-radius:2px;overflow:hidden;margin:10px 0 0}
.bar>div{height:100%;width:0;background:var(--accent);transition:width .4s ease}
footer{margin-top:34px;padding-top:16px;border-top:1px solid var(--line);
  font-size:12.5px;color:var(--muted)}
footer a{color:var(--accent);text-decoration:none}
__SHARED_CSS__
</style>
</head>
<body>
<div class="wrap">
  <h1>Mondegreen</h1>
  <p class="tag">用語集を、お願いではなく<b>制約</b>にする。 &nbsp;/&nbsp;
     <i>A private glossary, compiled into a hard phonetic constraint.</i> &nbsp;
     <span style="opacity:.6">v__VERSION__</span></p>

  <div class="privacy">
    <b>このページはサーバーに何も送りません。</b>
    Python はあなたのブラウザの中（Pyodide / WebAssembly）で動作します。
    用語集も書き起こしも Hugging Face のサーバーに到達しません。
    読み込み後はネットワークを切っても動きます。
  </div>

  <div class="warn">
    <b>ブラウザ実行の違い:</b> 形態素解析器 <code>fugashi</code> は C 拡張のため
    ブラウザでは動かず、内蔵の漢字読み表（4,030 字）を使っています。品詞が分からないと
    「稼働」（一般語・触ってはいけない）と「進藤」（固有名詞・訂正対象）を区別できないため、
    このビルドでは<b>制約側を厳しくして</b>対応しています —
    漢字スパンは<b>ほぼ完全な同音異義語にしか置換できません</b>。
    その結果、破壊率は上げずに再現率だけが少し下がります。
    フル機能は <code>pip install 'mondegreen[g2p]'</code> で。
  </div>

  <div class="grid">
    <div>
      <label for="transcript">Whisper 出力 / ASR transcript</label>
      <textarea id="transcript" spellcheck="false">__EXAMPLE_TRANSCRIPT__</textarea>
    </div>
    <div>
      <label for="glossary">用語集 / glossary (CSV: surface,reading,category)</label>
      <textarea id="glossary" spellcheck="false">__EXAMPLE_GLOSSARY__</textarea>
    </div>
  </div>

  <div class="controls">
    <div class="ctl">
      <div class="row"><span>τ — 硬い音韻距離の上限</span><b id="tauv">0.28</b></div>
      <input type="range" id="tau" min="0.05" max="0.5" step="0.01" value="0.28" />
    </div>
    <div class="ctl">
      <div class="row"><span>ゲート閾値 / conservative gate</span><b id="gatev">0.50</b></div>
      <input type="range" id="gate" min="0" max="1" step="0.01" value="0.5" />
    </div>
    <label class="chk"><input type="checkbox" id="halluc" checked /> 定型幻聴を除去する</label>
    <label class="chk"><input type="checkbox" id="soft" /> (B) プロンプト注入版も表示</label>
    <button id="go" disabled>読み込み中…</button>
  </div>
  <div class="bar"><div id="prog"></div></div>
  <div class="status" id="status">Pyodide（ブラウザ用 Python）を読み込んでいます…</div>

  <div class="tabs">
    <button class="tab active" data-p="diff">差分 / Diff</button>
    <button class="tab" data-p="evidence">根拠 / Evidence</button>
    <button class="tab" data-p="stats">統計 / Stats</button>
    <button class="tab" data-p="softp">(B) プロンプト注入</button>
  </div>
  <div class="panel active" id="p-diff"><div id="diff"></div>
    <label style="margin-top:16px">訂正後のテキスト</label>
    <textarea id="outtext" readonly style="min-height:120px"></textarea></div>
  <div class="panel" id="p-evidence">
    <p class="note">各訂正について <b>元の音韻列 / 候補 / 音韻距離</b> を表示します。
       <b>却下された候補も</b>表示されます — 制約の境界がどこにあるかが見えるように。</p>
    <div id="evidence"></div></div>
  <div class="panel" id="p-stats"><pre id="stats"></pre></div>
  <div class="panel" id="p-softp"><pre id="softp"></pre></div>

  <footer>
    <a href="https://github.com/NagaYu/mondegreen">GitHub</a> &nbsp;·&nbsp;
    <a href="https://huggingface.co/NagaYu/mondegreen">Model</a> &nbsp;·&nbsp;
    <a href="https://huggingface.co/datasets/NagaYu/mondegreen-asr-errors">Dataset</a>
    <p><b>利用範囲:</b> 用語集に個人名を含める機能があります。
       <b>利用者が自分の管理下にあるデータでのみ使用してください。</b>
       他人の会議記録や、同意を得ていない人物の名前を含む用語集を投入しないでください。</p>
  </footer>
</div>

<script id="payload" type="application/base64">__PAYLOAD__</script>
<script type="module">
const $ = id => document.getElementById(id);
const setStatus = (t) => { $("status").textContent = t; };
const setProg = (p) => { $("prog").style.width = p + "%"; };

document.querySelectorAll(".tab").forEach(b => b.onclick = () => {
  document.querySelectorAll(".tab").forEach(x => x.classList.remove("active"));
  document.querySelectorAll(".panel").forEach(x => x.classList.remove("active"));
  b.classList.add("active");
  $("p-" + b.dataset.p).classList.add("active");
});
$("tau").oninput = e => $("tauv").textContent = (+e.target.value).toFixed(2);
$("gate").oninput = e => $("gatev").textContent = (+e.target.value).toFixed(2);

let py = null;

async function boot() {
  try {
    setProg(10);
    const mod = await import("__PYODIDE__pyodide.mjs");
    setStatus("Python 処理系を初期化しています…"); setProg(35);
    py = await mod.loadPyodide({ indexURL: "__PYODIDE__" });
    setStatus("numpy を読み込んでいます…"); setProg(60);
    await py.loadPackage("numpy");
    setStatus("Mondegreen を展開しています…"); setProg(80);

    const b64 = document.getElementById("payload").textContent.trim();
    const bin = Uint8Array.from(atob(b64), c => c.charCodeAt(0));
    const files = JSON.parse(new TextDecoder("utf-8").decode(bin));
    for (const [path, content] of Object.entries(files)) {
      const dir = path.split("/").slice(0, -1).join("/");
      if (dir) { try { py.FS.mkdirTree(dir); } catch (e) {} }
      py.FS.writeFile(path, new TextEncoder().encode(content));
    }
    py.runPython(`
import sys
sys.path.insert(0, "")
from mondegreen.report import run_json
`);
    setProg(100);
    const n = Object.keys(files).length;
    setStatus(`準備完了 — ${n} ファイルをブラウザ内に展開しました。ネットワークは以後不要です。`);
    $("go").disabled = false;
    $("go").textContent = "訂正する / Correct";
    correct();
  } catch (e) {
    setStatus("読み込みに失敗しました: " + e);
    setProg(0);
    console.error(e);
  }
}

function correct() {
  if (!py) return;
  $("go").disabled = true;
  const t0 = performance.now();
  try {
    const fn = py.globals.get("run_json");
    const raw = fn(
      $("transcript").value, $("glossary").value,
      parseFloat($("tau").value), parseFloat($("gate").value),
      $("halluc").checked, "models/gate.json", $("soft").checked
    );
    const out = JSON.parse(raw);
    fn.destroy();
    $("diff").innerHTML = out.diff_html;
    $("evidence").innerHTML = out.evidence_html;
    $("outtext").value = out.text;
    $("stats").textContent = JSON.stringify(out.stats, null, 2);
    $("softp").textContent = out.soft_prompt || "（チェックを入れると (B) の実際のプロンプトを表示します）";
    const ms = Math.round(performance.now() - t0);
    const s = out.stats;
    setStatus(`${s.corrections_applied} 件の訂正、${s.hallucinations_removed} 件の幻聴を除去 ` +
              `（用語集 ${s.glossary_terms} 語、${ms} ms、すべてブラウザ内）`);
  } catch (e) {
    setStatus("エラー: " + e);
    console.error(e);
  } finally {
    $("go").disabled = false;
  }
}

$("go").onclick = correct;
boot();
</script>
</body>
</html>
"""


def main() -> int:
    """Claim: SUPPORT."""
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="hf/static_space")
    args = ap.parse_args()
    path = build(args.out)
    files = collect_files()
    print(f"wrote {path} ({os.path.getsize(path)/1024:.0f} KB, mondegreen v{__version__})")
    print(f"  {len(files)} files embedded, {sum(len(v) for v in files.values())/1024:.0f} KB of source+data")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
