#!/usr/bin/env python3
"""Build the (error, gold) dataset and push it to the Hugging Face Hub.

The real pipeline
-----------------

    openly-licensed Japanese text
        -> TTS (several voices, speeds)
        -> acoustic degradation (noise, far-field RIR, telephone band)
        -> Whisper (several sizes)
        -> (hypothesis, gold) pair + pathology labels

The gold side is the text that went *into* TTS, so it is exact by construction.
No LLM grades anything at any point.

Licensing
---------

Every record carries ``source_corpus`` and ``source_license``.  This script
refuses to push a dataset whose licence field is unset or unverified -- see
``mondegreen.harvest.CORPUS_LICENSES``.  Note in particular that "Aozora Bunko"
is not a licence: individual works there carry their own copyright status and you
must check the 図書カード for each one.

Examples
--------
    # Simulated (no models needed) -- good for CI and for reproducing the figures
    python scripts/harvest_errors.py --mode simulated -n 4000 --out data/

    # Real: needs pyopenjtalk (or a local VOICEVOX) plus faster-whisper
    python scripts/harvest_errors.py --mode real -n 2000 --whisper-size small --out data/

    # Push to the Hub (requires `huggingface-cli login`)
    python scripts/harvest_errors.py --mode real -n 2000 --push-to your-org/mondegreen-asr-errors
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter
from typing import Dict, List

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mondegreen.glossary import load_glossary, save_glossary
from mondegreen.harvest import (
    CORPUS_LICENSES, ErrorHarvester, GlossaryBuilder, PathologySet, SentenceFactory,
    build_asr, build_tts, license_for, write_jsonl,
)
from mondegreen.types import ErrorPair


def build_dataset_card(args, stats: Dict[str, object]) -> str:
    """Write the HF dataset card, licence facts included.

    Claim: SUPPORT -- an unlabelled dataset is an unpublishable dataset.
    """
    lic = license_for(args.corpus)
    taxonomy = "\n".join(
        f"| `{row['label']}` | {row['ja']} | {row['how']} |"
        for row in PathologySet().describe()
    )
    counts = "\n".join(f"| `{k}` | {v} |" for k, v in sorted(stats["error_types"].items()))  # type: ignore[index]
    return f"""---
license: {"cc0-1.0" if args.corpus == "synthetic" else "other"}
language:
- ja
task_categories:
- automatic-speech-recognition
- text2text-generation
tags:
- asr-error-correction
- japanese
- whisper
- phonetics
pretty_name: Mondegreen ASR error pairs
size_categories:
- {"1K<n<10K" if stats["n"] < 10000 else "10K<n<100K"}
---

# Mondegreen ASR error pairs

`(ASR hypothesis, gold text)` pairs for Japanese ASR post-correction, produced by
running a real ASR system as an **error generator**.

## How it was made

```
{args.corpus} text -> TTS -> degradation (noise / far-field / telephone) -> {stats['asr_model']} -> hypothesis
```

The gold side is the exact text fed to TTS. **No LLM judges correctness anywhere
in this pipeline.**

- provenance: **{stats['provenance']}**
- pairs: {stats['n']}
- glossary terms used: {stats['glossary_terms']}
- acoustic conditions: {stats['conditions']}

## Source text and licence

| field | value |
| --- | --- |
| corpus | `{args.corpus}` |
| licence | {lic['license']} |
| verification | {lic['verify']} |
| url | {lic.get('url') or '—'} |

If you add a corpus, add it to `mondegreen.harvest.CORPUS_LICENSES` with a
verified licence first. The harvester refuses unknown corpora by design.

## Pathology labels

| label | 日本語 | how it is produced |
| --- | --- | --- |
{taxonomy}

Observed counts in this build:

| label | count |
| --- | --- |
{counts}

## Fields

| field | meaning |
| --- | --- |
| `id` | stable record id |
| `gold` | the text that was spoken (exact) |
| `hypothesis` | what the ASR returned |
| `glossary_terms` | glossary surfaces occurring in `gold` |
| `error_types` | pathology labels |
| `speaker`, `speed`, `snr_db`, `room` | acoustic condition |
| `asr_model` | which ASR produced the hypothesis |
| `source_corpus`, `source_license` | provenance of the gold text |
| `split` | train / test (disjoint speakers, sentences and glossaries) |
| `provenance` | `measured` (real TTS+ASR) or `simulated` |

## Intended use

Training and evaluating **post-correction** systems. Not for training ASR models.

## Privacy

All names in this dataset are **synthetic**, generated by
`mondegreen.harvest.GlossaryBuilder`. No real person's voice or name was used, and
no real meeting audio exists anywhere in this pipeline.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mode", choices=["simulated", "real"], default="simulated")
    ap.add_argument("-n", type=int, default=2000, help="sentences per split")
    ap.add_argument("--glossary-size", type=int, default=1200)
    ap.add_argument("--test-glossary-size", type=int, default=400)
    ap.add_argument("--corpus", default="synthetic", choices=sorted(CORPUS_LICENSES))
    ap.add_argument("--whisper-size", default="small")
    ap.add_argument("--tts", default="auto")
    ap.add_argument("--asr", default="auto")
    ap.add_argument("--seed", type=int, default=20260823)
    ap.add_argument("--out", default="data")
    ap.add_argument("--push-to", help="HF dataset repo id, e.g. your-org/mondegreen-asr-errors")
    ap.add_argument("--private", action="store_true")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    print(f"[1/5] building disjoint train/test glossaries "
          f"({args.glossary_size} / {args.test_glossary_size})")
    gb = GlossaryBuilder(seed=args.seed)
    train_g, test_g = gb.build_pair(args.glossary_size, args.test_glossary_size)
    save_glossary(train_g, os.path.join(args.out, "glossary_train.csv"))
    save_glossary(test_g, os.path.join(args.out, "glossary_test.csv"))
    overlap = set(train_g.surfaces()) & set(test_g.surfaces())
    assert not overlap, f"glossary leak: {sorted(overlap)[:5]}"

    print(f"[2/5] generating carrier sentences ({args.n} per split)")
    train_s = SentenceFactory(seed=args.seed).build(train_g, args.n)
    test_s = SentenceFactory(seed=args.seed + 31337).build(test_g, args.n // 2)
    seen = {s for s, _ in train_s}
    test_s = [(s, t) for s, t in test_s if s not in seen]

    tts = asr = None
    if args.mode == "real":
        print(f"[3/5] loading TTS ({args.tts}) and ASR ({args.asr}:{args.whisper_size})")
        tts = build_tts(args.tts)
        asr = build_asr(args.whisper_size, args.asr)
        print(f"      tts={getattr(tts, 'name', '?')}  asr={getattr(asr, 'name', '?')}")
    else:
        print("[3/5] simulated mode: no TTS or ASR will be loaded")

    harvester = ErrorHarvester(tts=tts, asr=asr, seed=args.seed)
    print(f"[4/5] harvesting ({args.mode})")
    pairs: List[ErrorPair] = []
    if args.mode == "real":
        pairs += harvester.harvest_real(train_s, train_g, split="train", corpus=args.corpus,
                                        asr_model=getattr(asr, "name", "whisper"))
        pairs += harvester.harvest_real(test_s, test_g, split="test", corpus=args.corpus,
                                        asr_model=getattr(asr, "name", "whisper"))
        pairs += harvester.harvest_hallucinations(split="train", corpus=args.corpus,
                                                  asr_model=getattr(asr, "name", "whisper"))
    else:
        pairs += harvester.harvest_simulated(train_s, train_g, split="train", corpus=args.corpus)
        pairs += harvester.harvest_simulated(test_s, test_g, split="test", corpus=args.corpus)

    path = os.path.join(args.out, "pairs.jsonl")
    write_jsonl(pairs, path)

    error_types = Counter(t for p in pairs for t in p.error_types)
    stats = {
        "n": len(pairs),
        "provenance": pairs[0].provenance if pairs else "unknown",
        "asr_model": pairs[0].asr_model if pairs else "unknown",
        "glossary_terms": len(train_g) + len(test_g),
        "conditions": sorted({f"{p.room}/{p.snr_db}" for p in pairs}),
        "error_types": dict(error_types),
    }
    with open(os.path.join(args.out, "stats.json"), "w", encoding="utf-8") as fh:
        json.dump(stats, fh, ensure_ascii=False, indent=2)
    card = build_dataset_card(args, stats)
    with open(os.path.join(args.out, "README.md"), "w", encoding="utf-8") as fh:
        fh.write(card)
    print(f"      {len(pairs)} pairs -> {path}")
    print(f"      labels: {dict(error_types)}")

    if not args.push_to:
        print("[5/5] not pushing (pass --push-to <repo-id> to publish)")
        return 0

    print(f"[5/5] pushing to https://huggingface.co/datasets/{args.push_to}")
    try:
        from datasets import Dataset, DatasetDict  # type: ignore
        from huggingface_hub import HfApi  # type: ignore
    except ImportError:
        print("  need: pip install 'mondegreen[harvest]'", file=sys.stderr)
        return 1

    for p in pairs:
        if not p.source_license or "REQUIRED" in p.source_license:
            print(f"  refusing to push: record {p.id} has an unverified licence "
                  f"({p.source_license!r}). Verify the source and set it in "
                  f"CORPUS_LICENSES first.", file=sys.stderr)
            return 2

    rows = [p.to_dict() for p in pairs]
    dd = DatasetDict({
        split: Dataset.from_list([r for r in rows if r["split"] == split])
        for split in sorted({r["split"] for r in rows})
    })
    dd.push_to_hub(args.push_to, private=args.private)
    api = HfApi()
    api.upload_file(
        path_or_fileobj=card.encode("utf-8"), path_in_repo="README.md",
        repo_id=args.push_to, repo_type="dataset",
    )
    for name in ("glossary_train.csv", "glossary_test.csv"):
        api.upload_file(
            path_or_fileobj=os.path.join(args.out, name), path_in_repo=name,
            repo_id=args.push_to, repo_type="dataset",
        )
    print("  done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
