"""Data construction: turn a real ASR system into an error generator.

Three builders, in the order the brief lays them out.

1. :class:`ErrorHarvester` -- take openly-licensed Japanese text, speak it with
   TTS under several voices, speeds, noise levels and room responses, run the
   result back through Whisper, and keep the ``(hypothesis, gold)`` pair.  The
   gold side is the text we fed to TTS, so it is exact by construction.  **No LLM
   grades anything, anywhere in this pipeline.**

2. :class:`PathologySet` -- deliberately reproduce the known failure modes:
   silence and noise-only regions that provoke canned hallucinations, dropped
   words, dropped particles, wrong numbers and units, and phonetic substitution
   of proper nouns.  Every pair carries a pathology label.

3. :class:`GlossaryBuilder` -- synthesise private vocabularies (people, products,
   jargon) *with readings*, write carrier sentences containing them, and push
   those through the same TTS -> ASR loop to manufacture "the term came back
   broken" cases at scale.

Licensing is not an afterthought here.  Every :class:`~mondegreen.types.ErrorPair`
records the corpus it came from and that corpus's licence, and
``scripts/harvest_errors.py`` refuses to push a dataset with an unset licence
field.  See :data:`CORPUS_LICENSES` -- and read it before adding a source, because
"Aozora Bunko" is not itself a licence.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import random
import re
import time
from dataclasses import dataclass, field, asdict
from typing import Callable, Dict, Iterable, Iterator, List, Optional, Sequence, Tuple

from .glossary import Glossary
from .hallucination import DEFAULT_PATTERNS
from .phonetics import DEFAULT_CONFIG, PhoneticConfig, to_katakana
from .simulate import ASRErrorSimulator, CorruptionConfig
from .types import ErrorPair, GlossaryEntry

# --------------------------------------------------------------------------------------
# Licensing
# --------------------------------------------------------------------------------------

#: Licence facts for the corpora this harvester knows how to read.  These are
#: *defaults for the collection*, not a substitute for checking the individual
#: work -- Aozora Bunko in particular hosts both public-domain texts and texts
#: under a CC licence chosen by a modern translator or transcriber.
CORPUS_LICENSES: Dict[str, Dict[str, str]] = {
    "aozora": {
        "license": "PublicDomain-or-CC-BY (per work)",
        "verify": "REQUIRED: each Aozora work carries its own 底本 and copyright status. "
                  "Check the per-work 図書カード before including it.",
        "url": "https://www.aozora.gr.jp/",
    },
    "wikipedia-ja": {
        "license": "CC-BY-SA-4.0",
        "verify": "Attribution and share-alike apply to the derived dataset.",
        "url": "https://ja.wikipedia.org/",
    },
    "e-gov": {
        "license": "CC-BY-4.0 (政府標準利用規約 第2.0版)",
        "verify": "Japanese government open data terms; attribution required.",
        "url": "https://www.e-gov.go.jp/",
    },
    "jrc-acquis-ja": {
        "license": "Check upstream",
        "verify": "REQUIRED",
        "url": "",
    },
    "synthetic": {
        "license": "CC0-1.0",
        "verify": "Generated by mondegreen.harvest.SentenceFactory; no third-party text.",
        "url": "",
    },
}


def license_for(corpus: str) -> Dict[str, str]:
    """Look up the licence record for a corpus, refusing unknown names.

    Claim: SUPPORT -- an unlabelled corpus cannot be published, so this raises
    rather than defaulting.
    """
    if corpus not in CORPUS_LICENSES:
        raise KeyError(
            f"unknown corpus {corpus!r}: add it to CORPUS_LICENSES with a verified "
            "licence before harvesting from it"
        )
    return CORPUS_LICENSES[corpus]


# --------------------------------------------------------------------------------------
# GlossaryBuilder
# --------------------------------------------------------------------------------------

_SURNAMES: Tuple[Tuple[str, str], ...] = (
    ("佐藤", "サトウ"), ("鈴木", "スズキ"), ("高橋", "タカハシ"), ("田中", "タナカ"),
    ("伊藤", "イトウ"), ("渡辺", "ワタナベ"), ("山本", "ヤマモト"), ("中村", "ナカムラ"),
    ("小林", "コバヤシ"), ("加藤", "カトウ"), ("吉田", "ヨシダ"), ("山田", "ヤマダ"),
    ("佐々木", "ササキ"), ("山口", "ヤマグチ"), ("松本", "マツモト"), ("井上", "イノウエ"),
    ("木村", "キムラ"), ("林", "ハヤシ"), ("斎藤", "サイトウ"), ("清水", "シミズ"),
    ("山崎", "ヤマザキ"), ("森", "モリ"), ("池田", "イケダ"), ("橋本", "ハシモト"),
    ("阿部", "アベ"), ("石川", "イシカワ"), ("山下", "ヤマシタ"), ("中島", "ナカジマ"),
    ("石井", "イシイ"), ("小川", "オガワ"), ("前田", "マエダ"), ("岡田", "オカダ"),
    ("長谷川", "ハセガワ"), ("藤田", "フジタ"), ("後藤", "ゴトウ"), ("近藤", "コンドウ"),
    ("村上", "ムラカミ"), ("遠藤", "エンドウ"), ("青木", "アオキ"), ("坂本", "サカモト"),
    ("新藤", "シンドウ"), ("神田", "カンダ"), ("宮崎", "ミヤザキ"), ("大谷", "オオタニ"),
    ("上原", "ウエハラ"), ("城田", "シロタ"), ("葛西", "カサイ"), ("鵜飼", "ウカイ"),
    ("福田", "フクダ"), ("太田", "オオタ"), ("三浦", "ミウラ"), ("藤井", "フジイ"),
    ("岡本", "オカモト"), ("松田", "マツダ"), ("中川", "ナカガワ"), ("中野", "ナカノ"),
    ("原田", "ハラダ"), ("小野", "オノ"), ("田村", "タムラ"), ("竹内", "タケウチ"),
    ("金子", "カネコ"), ("和田", "ワダ"), ("中山", "ナカヤマ"), ("石田", "イシダ"),
    ("上田", "ウエダ"), ("森田", "モリタ"), ("原", "ハラ"), ("柴田", "シバタ"),
    ("酒井", "サカイ"), ("工藤", "クドウ"), ("横山", "ヨコヤマ"), ("宮本", "ミヤモト"),
    ("内田", "ウチダ"), ("高木", "タカギ"), ("安藤", "アンドウ"), ("島田", "シマダ"),
    ("谷口", "タニグチ"), ("大野", "オオノ"), ("高田", "タカダ"), ("丸山", "マルヤマ"),
    ("今井", "イマイ"), ("河野", "コウノ"), ("藤本", "フジモト"), ("村田", "ムラタ"),
    ("武田", "タケダ"), ("上野", "ウエノ"), ("杉山", "スギヤマ"), ("増田", "マスダ"),
    ("小島", "コジマ"), ("平野", "ヒラノ"), ("大塚", "オオツカ"), ("千葉", "チバ"),
    ("久保田", "クボタ"), ("松井", "マツイ"), ("岩崎", "イワサキ"), ("桜井", "サクライ"),
    ("野口", "ノグチ"), ("松尾", "マツオ"), ("野中", "ノナカ"), ("菅原", "スガワラ"),
    ("荒木", "アラキ"), ("大西", "オオニシ"), ("菊地", "キクチ"), ("岩田", "イワタ"),
    ("小山", "コヤマ"), ("樋口", "ヒグチ"), ("北村", "キタムラ"), ("安田", "ヤスダ"),
)

_GIVEN: Tuple[Tuple[str, str], ...] = (
    ("太郎", "タロウ"), ("次郎", "ジロウ"), ("健一", "ケンイチ"), ("直樹", "ナオキ"),
    ("翔太", "ショウタ"), ("大輔", "ダイスケ"), ("拓也", "タクヤ"), ("涼介", "リョウスケ"),
    ("美咲", "ミサキ"), ("彩香", "アヤカ"), ("由紀", "ユキ"), ("智子", "トモコ"),
    ("恵美", "エミ"), ("陽子", "ヨウコ"), ("千夏", "チナツ"), ("真央", "マオ"),
    ("啓介", "ケイスケ"), ("和樹", "カズキ"), ("秀樹", "ヒデキ"), ("紗綾", "サアヤ"),
    ("怜", "レイ"), ("蓮", "レン"), ("葵", "アオイ"), ("楓", "カエデ"),
    ("優", "ユウ"), ("翼", "ツバサ"), ("結衣", "ユイ"), ("咲希", "サキ"),
    ("優真", "ユウマ"), ("悠斗", "ユウト"), ("陽菜", "ヒナ"), ("心春", "コハル"),
    ("将平", "ショウヘイ"), ("裕介", "ユウスケ"), ("俊介", "シュンスケ"), ("康平", "コウヘイ"),
    ("千尋", "チヒロ"), ("菜月", "ナツキ"), ("琴音", "コトネ"), ("莉子", "リコ"),
    ("大地", "ダイチ"), ("光輝", "コウキ"), ("竜也", "タツヤ"), ("聡", "サトシ"),
("千秋", "チアキ"), ("香織", "カオリ"), ("麻衣", "マイ"),
    ("洋平", "ヨウヘイ"), ("圭吾", "ケイゴ"), ("拓真", "タクマ"), ("隼人", "ハヤト"),
    ("美穂", "ミホ"), ("直美", "ナオミ"), ("裕子", "ユウコ"), ("久美子", "クミコ"),
)

_PRODUCT_HEADS: Tuple[Tuple[str, str], ...] = (
    ("ミライ", "ミライ"), ("ソラ", "ソラ"), ("ネクサス", "ネクサス"), ("アトラス", "アトラス"),
    ("オリオン", "オリオン"), ("カナデ", "カナデ"), ("ハヤブサ", "ハヤブサ"), ("ヒスイ", "ヒスイ"),
    ("コトダマ", "コトダマ"), ("シグマ", "シグマ"), ("ルミナ", "ルミナ"), ("テラ", "テラ"),
    ("アカツキ", "アカツキ"), ("ツバサ", "ツバサ"), ("イズミ", "イズミ"), ("クオン", "クオン"),
    ("カグヤ", "カグヤ"), ("ヤマト", "ヤマト"), ("スバル", "スバル"), ("ホクト", "ホクト"),
    ("セイレン", "セイレン"), ("ノヴァ", "ノヴァ"), ("プリズム", "プリズム"), ("フェニクス", "フェニクス"),
    ("アリア", "アリア"), ("ヴェルデ", "ヴェルデ"), ("ソレイユ", "ソレイユ"), ("ミストラル", "ミストラル"),
)
_PRODUCT_TAILS: Tuple[Tuple[str, str], ...] = (
    ("ドライブ", "ドライブ"), ("クラウド", "クラウド"), ("リンク", "リンク"), ("ゲート", "ゲート"),
    ("コア", "コア"), ("フロー", "フロー"), ("ブリッジ", "ブリッジ"), ("スタジオ", "スタジオ"),
    ("エンジン", "エンジン"), ("ハブ", "ハブ"), ("ミラー", "ミラー"), ("シェル", "シェル"),
    ("ボード", "ボード"), ("パネル", "パネル"), ("メッシュ", "メッシュ"), ("トラック", "トラック"),
    ("ワークス", "ワークス"), ("ラボ", "ラボ"), ("キャスト", "キャスト"), ("フォージ", "フォージ"),
)
_PRODUCT_SUFFIX: Tuple[str, ...] = ("", "", "", "X", "Pro", "2", "3", "Lite", "Neo")

_JARGON_A: Tuple[Tuple[str, str], ...] = (
    ("量子", "リョウシ"), ("分散", "ブンサン"), ("連合", "レンゴウ"), ("差分", "サブン"),
    ("疎行列", "ソギョウレツ"), ("多層", "タソウ"), ("動的", "ドウテキ"), ("再帰", "サイキ"),
    ("確率的", "カクリツテキ"), ("局所", "キョクショ"), ("階層", "カイソウ"), ("非線形", "ヒセンケイ"),
    ("音韻", "オンイン"), ("形態素", "ケイタイソ"), ("符号", "フゴウ"), ("整合", "セイゴウ"),
    ("双方向", "ソウホウコウ"), ("並列", "ヘイレツ"), ("逐次", "チクジ"), ("経験的", "ケイケンテキ"),
    ("勾配", "コウバイ"), ("残差", "ザンサ"), ("潜在", "センザイ"), ("疎", "ソ"),
    ("時系列", "ジケイレツ"), ("因果", "インガ"), ("変分", "ヘンブン"), ("敵対的", "テキタイテキ"),
    ("自己回帰", "ジコカイキ"), ("大域", "タイイキ"), ("辞書", "ジショ"), ("木構造", "キコウゾウ"),
)
_JARGON_B: Tuple[Tuple[str, str], ...] = (
    ("誤り訂正", "アヤマリテイセイ"), ("学習", "ガクシュウ"), ("推論", "スイロン"),
    ("最適化", "サイテキカ"), ("補正", "ホセイ"), ("圧縮", "アッシュク"), ("整列", "セイレツ"),
    ("復号", "フクゴウ"), ("量子化", "リョウシカ"), ("蒸留", "ジョウリュウ"),
    ("正則化", "セイソクカ"), ("展開", "テンカイ"), ("同定", "ドウテイ"), ("平滑化", "ヘイカツカ"),
    ("探索", "タンサク"), ("符号化", "フゴウカ"), ("分解", "ブンカイ"), ("近似", "キンジ"),
    ("検証", "ケンショウ"), ("適応", "テキオウ"), ("集約", "シュウヤク"), ("補間", "ホカン"),
    ("再構成", "サイコウセイ"), ("識別", "シキベツ"), ("抽出", "チュウシュツ"), ("評価", "ヒョウカ"),
)

_ORG_TAILS: Tuple[Tuple[str, str], ...] = (
    ("製作所", "セイサクショ"), ("工業", "コウギョウ"), ("商事", "ショウジ"),
    ("研究所", "ケンキュウジョ"), ("設計", "セッケイ"), ("技研", "ギケン"),
    ("電機", "デンキ"), ("精機", "セイキ"), ("運輸", "ウンユ"), ("建設", "ケンセツ"),
    ("食品", "ショクヒン"), ("化学", "カガク"), ("印刷", "インサツ"), ("物産", "ブッサン"),
)


@dataclass
class GlossaryBuilder:
    """Synthesise private vocabularies with readings, deterministically.

    Two properties matter for the evaluation to be honest:

    * **Determinism.**  Same seed, same glossary, so the 100 / 1,000 / 10,000
      conditions are nested subsets rather than three different vocabularies.
    * **Disjointness.**  :meth:`build_pair` returns train and test glossaries
      that share no surface form, no reading, and no name component -- the brief
      requires a test on terms the system has never seen, and near-duplicates
      would quietly leak.

    Claim: UNBOUNDED-VOCAB -- this is what generates the x-axis of the headline
    figure; TERM-RECALL -- and the terms it has to restore.
    """

    seed: int = 20260823

    def build(
        self,
        n: int,
        seed: Optional[int] = None,
        exclude: Optional[Glossary] = None,
        mix: Tuple[float, float, float, float] = (0.40, 0.25, 0.25, 0.10),
    ) -> Glossary:
        """Generate ``n`` unique entries: people, products, jargon, organisations.

        Claim: UNBOUNDED-VOCAB.
        """
        rng = random.Random(self.seed if seed is None else seed)
        banned_surfaces = {e.surface for e in (exclude or ())}
        banned_readings = {r for e in (exclude or ()) for r in e.all_readings()}
        g = Glossary()
        p_person, p_product, p_jargon, _ = mix
        guard = 0
        while len(g) < n and guard < n * 400:
            guard += 1
            r = rng.random()
            if r < p_person:
                entry = self._person(rng)
            elif r < p_person + p_product:
                entry = self._product(rng)
            elif r < p_person + p_product + p_jargon:
                entry = self._jargon(rng)
            else:
                entry = self._org(rng)
            if entry.surface in banned_surfaces or entry.reading in banned_readings:
                continue
            if entry.surface in g:
                continue
            g.add(entry)
        if len(g) < n:
            raise RuntimeError(
                f"could only generate {len(g)} of {n} unique terms; widen the morpheme pools"
            )
        return g

    def build_pair(
        self, n_train: int, n_test: int, seed: Optional[int] = None
    ) -> Tuple[Glossary, Glossary]:
        """Build train and *strictly disjoint* test glossaries.

        Claim: UNBOUNDED-VOCAB -- the "glossary never seen in training" condition
        the brief asks for is only meaningful if disjointness is enforced
        mechanically rather than assumed.
        """
        base = self.seed if seed is None else seed
        train = self.build(n_train, seed=base)
        test = self.build(n_test, seed=base + 7919, exclude=train)
        overlap = set(train.surfaces()) & set(test.surfaces())
        if overlap:  # pragma: no cover - build() already excludes
            raise AssertionError(f"train/test glossary overlap: {sorted(overlap)[:5]}")
        return train, test

    # -- generators --------------------------------------------------------
    def _person(self, rng: random.Random) -> GlossaryEntry:
        """Claim: TERM-RECALL -- personal names are the highest-value category."""
        s, sr = _SURNAMES[rng.randrange(len(_SURNAMES))]
        if rng.random() < 0.45:
            g, gr = _GIVEN[rng.randrange(len(_GIVEN))]
            return GlossaryEntry(s + g, sr + gr, category="person", weight=1.0)
        return GlossaryEntry(s, sr, category="person", weight=1.2)

    def _product(self, rng: random.Random) -> GlossaryEntry:
        """Claim: TERM-RECALL."""
        h, hr = _PRODUCT_HEADS[rng.randrange(len(_PRODUCT_HEADS))]
        t, tr = _PRODUCT_TAILS[rng.randrange(len(_PRODUCT_TAILS))]
        suf = _PRODUCT_SUFFIX[rng.randrange(len(_PRODUCT_SUFFIX))]
        surface = h + t + suf
        reading = hr + tr + _suffix_reading(suf)
        return GlossaryEntry(surface, reading, category="product", weight=1.0)

    def _jargon(self, rng: random.Random) -> GlossaryEntry:
        """Claim: TERM-RECALL."""
        a, ar = _JARGON_A[rng.randrange(len(_JARGON_A))]
        b, br = _JARGON_B[rng.randrange(len(_JARGON_B))]
        return GlossaryEntry(a + b, ar + br, category="jargon", weight=0.9)

    def _org(self, rng: random.Random) -> GlossaryEntry:
        """Claim: TERM-RECALL."""
        s, sr = _SURNAMES[rng.randrange(len(_SURNAMES))]
        t, tr = _ORG_TAILS[rng.randrange(len(_ORG_TAILS))]
        return GlossaryEntry(s + t, sr + tr, category="org", weight=0.9)


def _suffix_reading(suffix: str) -> str:
    """Claim: SUPPORT."""
    return {
        "": "", "X": "エックス", "Pro": "プロ", "2": "ツー", "3": "スリー",
        "Lite": "ライト", "Neo": "ネオ",
    }.get(suffix, "")


# --------------------------------------------------------------------------------------
# Carrier sentences
# --------------------------------------------------------------------------------------

_TEMPLATES: Tuple[str, ...] = (
    "{T0}さんから{T1}の件で連絡がありました。",
    "本日の議題は{T0}の進捗と{T1}の予算です。",
    "{T0}を{N}台発注する件、{T1}に確認をお願いします。",
    "{T0}の仕様変更について、{T1}チームと調整しています。",
    "先週の会議で{T0}が指摘した{T1}の問題は解決済みです。",
    "{T0}の納期は{N}月{N2}日で、担当は{T1}です。",
    "{T1}の測定結果を{T0}に共有しました。",
    "{T0}と{T1}の比較検証を来週までにまとめます。",
    "資料の{N}ページに{T0}の説明があります。{T1}も参照してください。",
    "{T0}については{T1}が詳しいので、そちらに聞いてください。",
    "えーと、{T0}の話なんですけど、{T1}はどうなりましたか。",
    "{T0}の稼働率が{N}パーセントまで下がっています。{T1}の影響でしょうか。",
    "{T1}を導入する前に、{T0}の互換性を確認する必要があります。",
    "{T0}は{T1}に統合される予定です。",
    "見積もりは{N}万円で、{T0}と{T1}の両方を含みます。",
)


@dataclass
class SentenceFactory:
    """Generate carrier sentences that contain glossary terms.

    The templates are deliberately meeting-shaped -- hedges, fillers, numbers,
    honorifics -- because those are the constructions a post-corrector is most
    likely to damage, and a corpus of clean declaratives would hide that.

    Claim: LOW-DAMAGE -- the evaluation corpus has to contain the things that are
    easy to break, or the damage rate is measured on easy mode.
    """

    seed: int = 20260823
    license_name: str = "CC0-1.0"
    corpus: str = "synthetic"

    def build(
        self,
        glossary: Glossary,
        n: int,
        seed: Optional[int] = None,
        terms_per_sentence: int = 2,
    ) -> List[Tuple[str, Tuple[str, ...]]]:
        """Return ``n`` ``(sentence, terms_used)`` pairs.

        Claim: TERM-RECALL.
        """
        rng = random.Random(self.seed if seed is None else seed)
        entries = list(glossary)
        if not entries:
            return []
        out: List[Tuple[str, Tuple[str, ...]]] = []
        for i in range(n):
            tpl = _TEMPLATES[rng.randrange(len(_TEMPLATES))]
            picks = [entries[rng.randrange(len(entries))] for _ in range(terms_per_sentence)]
            text = (
                tpl.replace("{T0}", picks[0].surface)
                .replace("{T1}", picks[min(1, len(picks) - 1)].surface)
                .replace("{N2}", str(rng.randint(1, 28)))
                .replace("{N}", str(rng.randint(2, 99)))
            )
            out.append((text, tuple(dict.fromkeys(p.surface for p in picks))))
        return out


# --------------------------------------------------------------------------------------
# PathologySet
# --------------------------------------------------------------------------------------

@dataclass
class PathologySet:
    """The catalogue of known ASR failure modes, and how to provoke each one.

    Claim: SUPPORT -- metric (5) needs hallucination cases, and the per-class
    breakdown of metrics (1)-(3) needs every other label.
    """

    patterns: Tuple[str, ...] = DEFAULT_PATTERNS
    #: Seconds of silence / noise-only audio to append when provoking
    #: hallucinations with the real (audio) harvester.
    silence_seconds: Tuple[float, ...] = (1.5, 3.0, 6.0)
    noise_only_seconds: Tuple[float, ...] = (2.0, 5.0)

    def describe(self) -> List[Dict[str, str]]:
        """Human-readable taxonomy, rendered into the dataset card.

        Claim: SUPPORT.
        """
        return [
            {"label": "term-phonetic", "ja": "固有名詞の音韻的置換",
             "how": "glossary term rendered as a homophone or near-homophone"},
            {"label": "voicing", "ja": "濁音・清音の取り違え",
             "how": "rendaku / devoicing slip inside a term"},
            {"label": "long-vowel", "ja": "長音の脱落・付加",
             "how": "chouon added or dropped"},
            {"label": "geminate", "ja": "促音の脱落・付加",
             "how": "sokuon added or dropped"},
            {"label": "moraic-nasal", "ja": "撥音の脱落",
             "how": "moraic nasal swallowed, typically in far-field audio"},
            {"label": "particle-drop", "ja": "助詞の欠落",
             "how": "unstressed particle lost"},
            {"label": "word-drop", "ja": "語の脱落",
             "how": "short span deleted entirely"},
            {"label": "number-unit", "ja": "数字・単位の誤り",
             "how": "digit or counter substituted"},
            {"label": "hallucination", "ja": "定型の幻聴",
             "how": "canned phrase emitted over silence or noise-only audio"},
        ]

    def silence_probes(self) -> List[Dict[str, object]]:
        """Audio specs whose only purpose is to make Whisper hallucinate.

        Used by the real harvester: synthesise these, transcribe them, and record
        whatever comes out.  Anything non-empty is a hallucination by
        construction, because the audio contains no speech.

        Claim: SUPPORT -- metric (5)'s numerator comes from exactly this.
        """
        probes: List[Dict[str, object]] = []
        for s in self.silence_seconds:
            probes.append({"kind": "silence", "seconds": s, "gold": ""})
        for s in self.noise_only_seconds:
            for snr in (-5.0, 0.0):
                probes.append({"kind": "noise", "seconds": s, "snr_db": snr, "gold": ""})
        return probes


# --------------------------------------------------------------------------------------
# Audio degradation
# --------------------------------------------------------------------------------------

@dataclass
class DegradationSpec:
    """One acoustic condition: speed, noise, room, band.

    Claim: SUPPORT -- ASR errors are a function of the channel, so the corpus has
    to span channels or it only measures one.
    """

    speed: float = 1.0
    snr_db: Optional[float] = None
    room: str = "close"       # close / far / reverb
    band: str = "wide"        # wide / telephone
    label: str = "clean"

    def to_dict(self) -> Dict[str, object]:
        """Claim: SUPPORT."""
        return asdict(self)


DEFAULT_DEGRADATIONS: Tuple[DegradationSpec, ...] = (
    DegradationSpec(1.00, None, "close", "wide", "clean"),
    DegradationSpec(1.15, 20.0, "close", "wide", "fast-clean"),
    DegradationSpec(0.90, 15.0, "close", "wide", "slow-noisy"),
    DegradationSpec(1.00, 10.0, "far", "wide", "far-field"),
    DegradationSpec(1.05, 5.0, "reverb", "wide", "reverb-noisy"),
    DegradationSpec(1.00, 12.0, "far", "telephone", "telephone"),
)


def degrade(audio, sample_rate: int, spec: DegradationSpec, seed: int = 0):
    """Apply a degradation spec to a waveform.

    Speed change by resampling, additive noise at a target SNR, a synthetic
    exponential-decay room impulse response for the far/reverb conditions, and a
    band-limit for the telephone condition.  Requires numpy; scipy is used for
    the filters when available.

    Claim: SUPPORT -- these are the conditions that generate the errors
    TERM-RECALL is measured on.
    """
    import numpy as np

    x = np.asarray(audio, dtype=np.float64)
    rng = np.random.default_rng(seed)

    if abs(spec.speed - 1.0) > 1e-3:
        n_out = int(len(x) / spec.speed)
        idx = np.linspace(0, len(x) - 1, n_out)
        x = np.interp(idx, np.arange(len(x)), x)

    if spec.room in ("far", "reverb"):
        rt60 = 0.35 if spec.room == "far" else 0.75
        n = int(rt60 * sample_rate)
        t = np.arange(n) / sample_rate
        rir = rng.normal(0, 1, n) * np.exp(-6.9 * t / rt60)
        rir[0] += 1.0
        rir /= np.sqrt(np.sum(rir ** 2)) or 1.0
        x = np.convolve(x, rir)[: len(x) + n - 1]
        if spec.room == "far":
            x *= 0.4

    if spec.band == "telephone":
        try:
            from scipy.signal import butter, sosfilt  # type: ignore

            sos = butter(4, [300 / (sample_rate / 2), 3400 / (sample_rate / 2)],
                         btype="band", output="sos")
            x = sosfilt(sos, x)
        except Exception:
            # Crude fallback band-limit: one-pole high pass + moving-average low pass.
            x = np.diff(np.concatenate([[0.0], x]))
            k = max(1, sample_rate // 6800)
            x = np.convolve(x, np.ones(k) / k, mode="same")

    if spec.snr_db is not None:
        sig_pow = float(np.mean(x ** 2)) or 1e-12
        noise = rng.normal(0, 1, len(x))
        noise_pow = float(np.mean(noise ** 2)) or 1e-12
        scale = math.sqrt(sig_pow / (noise_pow * (10 ** (spec.snr_db / 10.0))))
        x = x + scale * noise

    peak = float(np.max(np.abs(x))) or 1.0
    return (x / peak * 0.95).astype("float32")


# --------------------------------------------------------------------------------------
# ErrorHarvester
# --------------------------------------------------------------------------------------

class ErrorHarvester:
    """Use a real ASR system as an error generator, or simulate one.

    ``mode="real"`` runs text -> TTS -> degradation -> Whisper.  ``mode="simulated"``
    runs the phonetic corruption model in :mod:`mondegreen.simulate`.  Both emit
    the same :class:`~mondegreen.types.ErrorPair` records, distinguished by their
    ``provenance`` field, and nothing downstream is allowed to mix them silently.

    Claim: SUPPORT -- this is the source of every number in the benchmark.
    """

    def __init__(
        self,
        tts: Optional[Callable[[str], Tuple[object, int]]] = None,
        asr: Optional[Callable[[object, int], str]] = None,
        degradations: Sequence[DegradationSpec] = DEFAULT_DEGRADATIONS,
        pathologies: Optional[PathologySet] = None,
        simulator: Optional[ASRErrorSimulator] = None,
        seed: int = 20260823,
    ) -> None:
        """Configure the harvester with TTS/ASR backends, or none for simulation.

                Claim: SUPPORT.
                """
        self.tts = tts
        self.asr = asr
        self.degradations = tuple(degradations)
        self.pathologies = pathologies or PathologySet()
        self.simulator = simulator or ASRErrorSimulator()
        self.seed = seed

    # ------------------------------------------------------------- simulated
    def harvest_simulated(
        self,
        sentences: Sequence[Tuple[str, Tuple[str, ...]]],
        glossary: Glossary,
        split: str = "train",
        corpus: str = "synthetic",
    ) -> List[ErrorPair]:
        """Generate pairs without any audio.

        Claim: SUPPORT.
        """
        lic = license_for(corpus)["license"]
        entries = list(glossary)
        out: List[ErrorPair] = []
        for i, (gold, terms) in enumerate(sentences):
            spec = self.degradations[i % len(self.degradations)]
            key = f"{split}-{i}"
            hyp, present, labels = self.simulator.corrupt(gold, entries, key=key)
            out.append(
                ErrorPair(
                    id=f"{corpus}-{split}-{i:06d}",
                    gold=gold,
                    hypothesis=hyp,
                    glossary_terms=present or terms,
                    error_types=labels,
                    speaker=f"sim-{i % 6}",
                    speed=spec.speed,
                    snr_db=spec.snr_db,
                    room=spec.room,
                    asr_model="simulated",
                    source_corpus=corpus,
                    source_license=lic,
                    split=split,
                    provenance="simulated",
                )
            )
        return out

    # ------------------------------------------------------------------ real
    def harvest_real(
        self,
        sentences: Sequence[Tuple[str, Tuple[str, ...]]],
        glossary: Glossary,
        split: str = "train",
        corpus: str = "synthetic",
        asr_model: str = "whisper",
        speakers: Sequence[str] = ("default",),
        progress: bool = True,
    ) -> List[ErrorPair]:
        """The real thing: speak each sentence, degrade it, transcribe it.

        Requires ``tts`` and ``asr`` callables (see :func:`build_tts` and
        :func:`build_asr`).  Raises rather than silently degrading to simulation,
        because a run that quietly stopped being real would poison the model card.

        Claim: SUPPORT.
        """
        if self.tts is None or self.asr is None:
            raise RuntimeError(
                "harvest_real needs both a TTS and an ASR backend. "
                "Install extras: pip install 'mondegreen[harvest,g2p]', or pass "
                "tts=/asr= explicitly. Refusing to fall back to simulation."
            )
        lic = license_for(corpus)["license"]
        out: List[ErrorPair] = []
        n = len(sentences)
        for i, (gold, terms) in enumerate(sentences):
            spec = self.degradations[i % len(self.degradations)]
            speaker = speakers[i % len(speakers)]
            wav, sr = self.tts(gold)
            wav = degrade(wav, sr, spec, seed=self.seed + i)
            hyp = self.asr(wav, sr)
            present = tuple(t for t in terms if t in gold)
            out.append(
                ErrorPair(
                    id=f"{corpus}-{split}-{i:06d}",
                    gold=gold,
                    hypothesis=hyp,
                    glossary_terms=present,
                    error_types=label_pair(gold, hyp, present),
                    speaker=speaker,
                    speed=spec.speed,
                    snr_db=spec.snr_db,
                    room=spec.room,
                    asr_model=asr_model,
                    source_corpus=corpus,
                    source_license=lic,
                    split=split,
                    provenance="measured",
                )
            )
            if progress and (i % 25 == 0 or i == n - 1):
                print(f"  harvest {split}: {i + 1}/{n}", flush=True)
        return out

    def harvest_hallucinations(
        self, split: str = "train", asr_model: str = "whisper", corpus: str = "synthetic"
    ) -> List[ErrorPair]:
        """Transcribe pure silence and noise, and keep whatever Whisper invents.

        Gold is the empty string, so every non-empty transcription is a
        hallucination with no judgement call involved.

        Claim: SUPPORT -- metric (5).
        """
        if self.tts is None or self.asr is None:
            raise RuntimeError("harvest_hallucinations needs a real ASR backend")
        import numpy as np

        lic = license_for(corpus)["license"]
        out: List[ErrorPair] = []
        sr = 16000
        for i, probe in enumerate(self.pathologies.silence_probes()):
            n = int(float(probe["seconds"]) * sr)
            if probe["kind"] == "silence":
                wav = np.zeros(n, dtype="float32")
            else:
                rng = np.random.default_rng(self.seed + i)
                wav = (rng.normal(0, 0.02, n)).astype("float32")
            hyp = self.asr(wav, sr)
            out.append(
                ErrorPair(
                    id=f"{corpus}-{split}-halluc-{i:04d}",
                    gold="",
                    hypothesis=hyp,
                    glossary_terms=(),
                    error_types=("hallucination",) if hyp.strip() else (),
                    speaker="none",
                    snr_db=probe.get("snr_db"),  # type: ignore[arg-type]
                    room="close",
                    asr_model=asr_model,
                    source_corpus=corpus,
                    source_license=lic,
                    split=split,
                    provenance="measured",
                )
            )
        return out


def label_pair(gold: str, hypothesis: str, terms: Sequence[str]) -> Tuple[str, ...]:
    """Assign pathology labels to a *measured* pair by comparing gold and hypothesis.

    Deterministic rules only -- string containment, length deltas, digit
    comparison, hallucination pattern matching.  No model decides a label.

    Claim: SUPPORT -- the labels have to be reproducible for the per-class
    breakdown to mean anything.
    """
    labels: List[str] = []
    for t in terms:
        if t and t not in hypothesis:
            labels.append("term-phonetic")
            break
    if len(hypothesis) < len(gold) * 0.85:
        labels.append("word-drop")
    gold_digits = re.findall(r"[0-9０-９]", gold)
    hyp_digits = re.findall(r"[0-9０-９]", hypothesis)
    if gold_digits != hyp_digits:
        labels.append("number-unit")
    for pat in DEFAULT_PATTERNS:
        if pat in hypothesis and pat not in gold:
            labels.append("hallucination")
            break
    if not labels and hypothesis != gold:
        labels.append("term-phonetic")
    return tuple(sorted(set(labels)))


# --------------------------------------------------------------------------------------
# Backends
# --------------------------------------------------------------------------------------

def build_tts(backend: str = "auto", speaker: Optional[str] = None):
    """Return a ``text -> (waveform, sample_rate)`` callable.

    Backends tried in order: ``pyopenjtalk`` (offline, multiple voices via
    speed/pitch), ``voicevox`` (local HTTP server, many speakers), ``coqui``.

    Claim: SUPPORT -- LOCAL-SPEED is about inference; harvesting may use whatever
    it likes, but it must be reproducible and offline-capable.
    """
    order = ("pyopenjtalk", "voicevox", "coqui") if backend in ("auto", "") else (backend,)
    errors: List[str] = []
    for name in order:
        try:
            if name == "pyopenjtalk":
                import pyopenjtalk  # type: ignore

                def _tts(text: str):
                    """Synthesise one utterance -> (waveform, sample_rate).

                                        Claim: SUPPORT.
                                        """
                    wav, sr = pyopenjtalk.tts(text)
                    import numpy as np

                    return (np.asarray(wav, dtype="float32") / 32768.0), sr

                _tts.name = "pyopenjtalk"  # type: ignore[attr-defined]
                return _tts
            if name == "voicevox":
                import requests  # type: ignore

                base = os.environ.get("VOICEVOX_URL", "http://127.0.0.1:50021")
                sid = int(speaker or os.environ.get("VOICEVOX_SPEAKER", "1"))

                def _tts(text: str):
                    """Synthesise one utterance -> (waveform, sample_rate).

                                        Claim: SUPPORT.
                                        """
                    import io
                    import numpy as np
                    import soundfile as sf  # type: ignore

                    q = requests.post(f"{base}/audio_query", params={"text": text, "speaker": sid}, timeout=30)
                    q.raise_for_status()
                    s = requests.post(f"{base}/synthesis", params={"speaker": sid}, json=q.json(), timeout=120)
                    s.raise_for_status()
                    data, sr = sf.read(io.BytesIO(s.content), dtype="float32")
                    return np.asarray(data), sr

                _tts.name = f"voicevox:{sid}"  # type: ignore[attr-defined]
                return _tts
            if name == "coqui":
                from TTS.api import TTS  # type: ignore

                model = TTS(os.environ.get("COQUI_MODEL", "tts_models/ja/kokoro/tacotron2-DDC"))

                def _tts(text: str):
                    """Synthesise one utterance -> (waveform, sample_rate).

                                        Claim: SUPPORT.
                                        """
                    import numpy as np

                    wav = model.tts(text)
                    return np.asarray(wav, dtype="float32"), int(model.synthesizer.output_sample_rate)

                _tts.name = "coqui"  # type: ignore[attr-defined]
                return _tts
        except Exception as exc:
            errors.append(f"{name}: {type(exc).__name__}: {exc}")
    raise RuntimeError("no TTS backend available: " + "; ".join(errors))


def build_asr(model_size: str = "small", backend: str = "auto", language: str = "ja",
              initial_prompt: Optional[str] = None):
    """Return a ``(waveform, sample_rate) -> text`` callable.

    ``initial_prompt`` is how condition (B) is actually run: pass the glossary
    string and Whisper will silently truncate it to 244 tokens.

    Claim: UNBOUNDED-VOCAB -- this is the real measurement of the ceiling that
    :func:`~mondegreen.baselines.whisper_prompt_capacity` predicts.
    """
    order = ("faster_whisper", "whisper", "transformers") if backend in ("auto", "") else (backend,)
    errors: List[str] = []
    for name in order:
        try:
            if name == "faster_whisper":
                from faster_whisper import WhisperModel  # type: ignore

                model = WhisperModel(model_size, device="auto", compute_type="int8")

                def _asr(wav, sr):
                    """Transcribe one waveform -> text.

                                        Claim: SUPPORT.
                                        """
                    import numpy as np

                    audio = _resample(np.asarray(wav, dtype="float32"), sr, 16000)
                    segments, _ = model.transcribe(
                        audio, language=language, initial_prompt=initial_prompt,
                        condition_on_previous_text=False,
                    )
                    return "".join(s.text for s in segments).strip()

                _asr.name = f"faster-whisper-{model_size}"  # type: ignore[attr-defined]
                return _asr
            if name == "whisper":
                import whisper  # type: ignore

                model = whisper.load_model(model_size)

                def _asr(wav, sr):
                    """Transcribe one waveform -> text.

                                        Claim: SUPPORT.
                                        """
                    import numpy as np

                    audio = _resample(np.asarray(wav, dtype="float32"), sr, 16000)
                    r = model.transcribe(audio, language=language, initial_prompt=initial_prompt,
                                         condition_on_previous_text=False)
                    return str(r.get("text", "")).strip()

                _asr.name = f"whisper-{model_size}"  # type: ignore[attr-defined]
                return _asr
            if name == "transformers":
                from transformers import pipeline  # type: ignore

                pipe = pipeline("automatic-speech-recognition", model=f"openai/whisper-{model_size}")

                def _asr(wav, sr):
                    """Transcribe one waveform -> text.

                                        Claim: SUPPORT.
                                        """
                    import numpy as np

                    audio = _resample(np.asarray(wav, dtype="float32"), sr, 16000)
                    out = pipe(audio, generate_kwargs={"language": language})
                    return str(out.get("text", "")).strip()

                _asr.name = f"transformers-whisper-{model_size}"  # type: ignore[attr-defined]
                return _asr
        except Exception as exc:
            errors.append(f"{name}: {type(exc).__name__}: {exc}")
    raise RuntimeError("no ASR backend available: " + "; ".join(errors))


def _resample(x, sr_in: int, sr_out: int):
    """Linear resample; adequate for 16 kHz ASR front ends.

    Claim: SUPPORT.
    """
    import numpy as np

    if sr_in == sr_out:
        return x
    n = int(len(x) * sr_out / sr_in)
    return np.interp(np.linspace(0, len(x) - 1, n), np.arange(len(x)), x).astype("float32")


# --------------------------------------------------------------------------------------
# Serialisation
# --------------------------------------------------------------------------------------

def write_jsonl(pairs: Sequence[ErrorPair], path: str) -> None:
    """Write pairs as JSONL.

    Claim: SUPPORT.
    """
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for p in pairs:
            fh.write(json.dumps(p.to_dict(), ensure_ascii=False) + "\n")


def read_jsonl(path: str) -> List[ErrorPair]:
    """Read pairs back from JSONL.

    Claim: SUPPORT.
    """
    out: List[ErrorPair] = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            d["glossary_terms"] = tuple(d.get("glossary_terms", ()))
            d["error_types"] = tuple(d.get("error_types", ()))
            out.append(ErrorPair(**d))
    return out
