"""A phonetically-grounded ASR error simulator.

Why this exists
===============

The real data path is ``scripts/harvest_errors.py``: public-domain Japanese text
-> TTS -> acoustic degradation -> Whisper -> ``(hypothesis, gold)`` pairs.  That
path needs a GPU, a TTS engine and several gigabytes of model weights, and it is
the path whose numbers go in the model card.

This module is the other path.  It corrupts gold text directly, using the *same*
phonology the corrector uses, so that the entire pipeline -- gate training,
benchmarks, figures, tests -- is runnable on a laptop with no models at all, and
so that CI can assert the invariants on thousands of examples in seconds.

Everything it produces is stamped ``provenance="simulated"``.  Simulated numbers
are never presented as measured ones: the benchmark runner keeps them in separate
files and the figure generator watermarks them.

What it models
==============

Each corruption is drawn from the pathology taxonomy the brief asks for, and the
phonetic ones are generated by perturbing the *reading* with exactly the
confusions the distance function discounts (voicing, long vowels, geminates,
sibilants) and then re-rendering that reading the way Whisper would: as katakana,
as hiragana, or -- most realistically -- as a homophone kanji spelling picked
from the bundled reading table.  A corrupted term therefore looks like 「進藤」
for 「新藤」, not like a random string.
"""

from __future__ import annotations

import random
import re
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from .glossary import Glossary
from .hallucination import DEFAULT_PATTERNS
from .phonetics import DEFAULT_CONFIG, PhoneticConfig, to_katakana
from .reading import char_kind, common_kanji, kanji_readings
from .types import ErrorPair, GlossaryEntry

#: Pathology labels.  Every generated error carries at least one.
PATHOLOGIES: Tuple[str, ...] = (
    "term-phonetic",     # 固有名詞の音韻的置換
    "voicing",           # 濁音・清音の取り違え
    "long-vowel",        # 長音の脱落・付加
    "geminate",          # 促音の脱落・付加
    "moraic-nasal",      # 撥音の脱落
    "particle-drop",     # 助詞の欠落
    "word-drop",         # 語の脱落
    "number-unit",       # 数字・単位の誤り
    "hallucination",     # 無音・雑音区間の定型幻聴
)

_VOICING = {"カ": "ガ", "キ": "ギ", "ク": "グ", "ケ": "ゲ", "コ": "ゴ",
            "サ": "ザ", "シ": "ジ", "ス": "ズ", "セ": "ゼ", "ソ": "ゾ",
            "タ": "ダ", "チ": "ヂ", "ツ": "ヅ", "テ": "デ", "ト": "ド",
            "ハ": "バ", "ヒ": "ビ", "フ": "ブ", "ヘ": "ベ", "ホ": "ボ"}
_UNVOICING = {v: k for k, v in _VOICING.items()}
_SIBILANT = {"シ": "ヒ", "ス": "ツ", "ジ": "ヂ", "チ": "ツ", "ツ": "チ", "サ": "シャ", "ザ": "ジャ"}
_VOWEL_SWAP = {"イ": "エ", "エ": "イ", "ウ": "オ", "オ": "ウ", "ア": "オ"}

_PARTICLES = ("は", "が", "を", "に", "へ", "と", "で", "も", "の", "や", "から", "まで")

_UNITS = ("キロ", "メートル", "グラム", "パーセント", "件", "名", "円", "時間", "分", "秒", "台", "個")
_DIGITS = "0123456789０１２３４５６７８９一二三四五六七八九十百千万"


@dataclass
class CorruptionConfig:
    """Per-phenomenon rates.  Stated assumptions, not measurements.

    Defaults are set so the simulated corpus has a term-level error rate in the
    same region as Whisper-small on far-field Japanese with out-of-vocabulary
    proper nouns -- roughly 55-70% of glossary terms mangled.  The exact value is
    reported in every benchmark file.

    Claim: SUPPORT.
    """

    term_error_rate: float = 0.62
    particle_drop_rate: float = 0.05
    word_drop_rate: float = 0.03
    number_error_rate: float = 0.18
    hallucination_rate: float = 0.12
    #: Probability a corrupted term is rendered as kanji (vs katakana/hiragana).
    kanji_render_rate: float = 0.55
    katakana_render_rate: float = 0.33
    #: How many phonetic perturbations to apply to one term's reading.
    max_perturbations: int = 2
    seed: int = 20260823

    def to_dict(self) -> Dict[str, float]:
        """Claim: SUPPORT."""
        return {k: float(v) for k, v in asdict(self).items()}


class HomophoneRenderer:
    """Write a kana reading back out as plausible (wrong) kanji.

    Builds a reading -> kanji reverse index from the bundled table, then greedily
    covers the reading with kanji, longest reading first.  The output is the kind
    of thing an ASR system actually emits for an unknown proper noun: real kanji,
    correct sound, wrong word.

    Claim: SUPPORT -- a simulator that produced random noise instead of
    homophones would make TERM-RECALL trivially easy and the whole benchmark
    meaningless.
    """

    def __init__(self, preferred: Optional[Iterable[str]] = None) -> None:
        #: Characters to draw from first.  Defaults to the bundled common set;
        #: the harvester passes the character inventory of the source corpus, so
        #: simulated errors stay inside the vocabulary the corpus itself uses.
        """Configure the simulator.

                Claim: SUPPORT.
                """
        self.preferred = frozenset(preferred) if preferred is not None else common_kanji()
        self._by_reading: Dict[str, List[str]] = defaultdict(list)
        self._preferred_by_reading: Dict[str, List[str]] = defaultdict(list)
        for kanji, readings in kanji_readings().items():
            for r in readings:
                r = to_katakana(r)
                if 1 <= len(r) <= 4:
                    self._by_reading[r].append(kanji)
                    if kanji in self.preferred:
                        self._preferred_by_reading[r].append(kanji)
        self._max_len = max((len(r) for r in self._by_reading), default=1)

    def render(self, reading: str, rng: random.Random, avoid: str = "") -> Optional[str]:
        """Greedy longest-match kanji spelling of ``reading``, or ``None``.

        ``avoid`` is the correct surface; if the greedy walk reproduces it we
        return ``None`` rather than emit a "corruption" that is actually right.

        Claim: SUPPORT.
        """
        kana = to_katakana(reading)
        out: List[str] = []
        i = 0
        while i < len(kana):
            hit = None
            for length in range(min(self._max_len, len(kana) - i), 0, -1):
                chunk = kana[i : i + length]
                pool = self._preferred_by_reading.get(chunk) or self._by_reading.get(chunk)
                if pool:
                    hit = (length, pool[rng.randrange(len(pool))])
                    break
            if hit is None:
                return None
            out.append(hit[1])
            i += hit[0]
        surface = "".join(out)
        if surface == avoid or len(surface) > 12:
            return None
        return surface


class ASRErrorSimulator:
    """Corrupt gold text into a plausible ASR hypothesis, with pathology labels.

    Claim: SUPPORT -- supplies the ``(error, gold)`` pairs that every metric in
    this repo is computed from when no GPU is available.
    """

    def __init__(
        self,
        config: Optional[CorruptionConfig] = None,
        phonetic_config: Optional[PhoneticConfig] = None,
        hallucination_patterns: Sequence[str] = DEFAULT_PATTERNS,
        corpus_chars: Optional[Iterable[str]] = None,
    ) -> None:
        """Configure the simulator.

                Claim: SUPPORT.
                """
        self.config = config or CorruptionConfig()
        self.phonetic_config = phonetic_config or DEFAULT_CONFIG
        self.hallucination_patterns = tuple(hallucination_patterns)
        self.renderer = HomophoneRenderer(preferred=corpus_chars)

    # ------------------------------------------------------------------ readings
    def perturb_reading(self, reading: str, rng: random.Random) -> Tuple[str, List[str]]:
        """Apply 1-2 realistic phonetic slips to a kana reading.

        The slips are drawn from the same confusion classes the distance function
        discounts.  That is deliberate and it is not circular: it means the
        simulated errors are *reachable* under the hard constraint, which is what
        makes the constraint's threshold the thing under test rather than a
        trivially-satisfied formality.  Errors outside the constraint are
        generated too (see :meth:`corrupt_term`), and those are the ones the
        corrector is *supposed* to miss.

        Claim: TERM-RECALL.
        """
        kana = list(to_katakana(reading))
        labels: List[str] = []
        n = rng.randint(1, max(1, self.config.max_perturbations))
        for _ in range(n):
            if not kana:
                break
            choice = rng.random()
            idx = rng.randrange(len(kana))
            ch = kana[idx]
            if choice < 0.30 and (ch in _VOICING or ch in _UNVOICING):
                kana[idx] = _VOICING.get(ch) or _UNVOICING.get(ch, ch)
                labels.append("voicing")
            elif choice < 0.50:
                if "ー" in kana:
                    kana.remove("ー")
                    labels.append("long-vowel")
                else:
                    kana.insert(min(idx + 1, len(kana)), "ー")
                    labels.append("long-vowel")
            elif choice < 0.65:
                if "ッ" in kana:
                    kana.remove("ッ")
                else:
                    kana.insert(min(idx + 1, len(kana)), "ッ")
                labels.append("geminate")
            elif choice < 0.78:
                if "ン" in kana:
                    kana.remove("ン")
                    labels.append("moraic-nasal")
                else:
                    kana[idx] = _VOWEL_SWAP.get(ch, ch)
                    labels.append("term-phonetic")
            elif choice < 0.90 and ch in _SIBILANT:
                kana[idx] = _SIBILANT[ch]
                labels.append("term-phonetic")
            else:
                kana[idx] = _VOWEL_SWAP.get(ch, ch)
                labels.append("term-phonetic")
        out = "".join(kana).strip("ー")
        return (out or to_katakana(reading)), labels

    def corrupt_term(
        self, entry: GlossaryEntry, rng: random.Random
    ) -> Tuple[str, List[str]]:
        """Produce one wrong-but-plausible surface for a glossary term.

        Claim: TERM-RECALL -- this is the thing condition (D) has to undo.
        """
        perturbed, labels = self.perturb_reading(entry.reading, rng)
        labels = labels or ["term-phonetic"]
        r = rng.random()
        # A katakana product name comes back from ASR as katakana, not as kanji.
        # Rendering it as kanji would be an error no real decoder makes.
        all_katakana = all(char_kind(c) in ("katakana",) for c in entry.surface)
        if all_katakana:
            return to_katakana(perturbed), labels
        if r < self.config.kanji_render_rate:
            kanji = self.renderer.render(perturbed, rng, avoid=entry.surface)
            if kanji:
                return kanji, labels + ["term-phonetic"]
        if r < self.config.kanji_render_rate + self.config.katakana_render_rate:
            return to_katakana(perturbed), labels
        from .phonetics import to_hiragana

        return to_hiragana(to_katakana(perturbed)), labels

    # ------------------------------------------------------------------- corrupt
    def corrupt(
        self,
        gold: str,
        entries: Sequence[GlossaryEntry],
        rng: Optional[random.Random] = None,
        key: str = "",
    ) -> Tuple[str, Tuple[str, ...], Tuple[str, ...]]:
        """Corrupt one sentence.

        Returns ``(hypothesis, terms_present_in_gold, pathology_labels)``.

        Claim: SUPPORT -- the returned term list is the denominator of metric (2)
        and the pathology labels are what makes metric (5) and the per-class
        breakdown possible.
        """
        rng = rng or random.Random(f"{self.config.seed}:{key or gold}")
        text = gold
        labels: List[str] = []
        present = tuple(e.surface for e in entries if e.surface and e.surface in gold)

        for surface in present:
            if rng.random() >= self.config.term_error_rate:
                continue
            entry = next(e for e in entries if e.surface == surface)
            wrong, lab = self.corrupt_term(entry, rng)
            if wrong and wrong != surface:
                text = text.replace(surface, wrong, 1)
                labels.extend(lab)

        text, lab = self._drop_particles(text, rng)
        labels.extend(lab)
        text, lab = self._drop_words(text, rng)
        labels.extend(lab)
        text, lab = self._mangle_numbers(text, rng)
        labels.extend(lab)
        text, lab = self._hallucinate(text, rng)
        labels.extend(lab)

        return text, present, tuple(sorted(set(labels)))

    # --------------------------------------------------------------- phenomena
    def _drop_particles(self, text: str, rng: random.Random) -> Tuple[str, List[str]]:
        """Delete a particle -- what far-field audio does to unstressed morae.

        Claim: SUPPORT (pathology class 「助詞の欠落」).
        """
        if rng.random() >= self.config.particle_drop_rate:
            return text, []
        positions = [
            i for i, ch in enumerate(text) if ch in _PARTICLES and 0 < i < len(text) - 1
        ]
        if not positions:
            return text, []
        i = positions[rng.randrange(len(positions))]
        return text[:i] + text[i + 1 :], ["particle-drop"]

    def _drop_words(self, text: str, rng: random.Random) -> Tuple[str, List[str]]:
        """Delete a short run of characters -- the 「語の脱落」 class.

        Claim: SUPPORT.
        """
        if rng.random() >= self.config.word_drop_rate or len(text) < 12:
            return text, []
        width = rng.randint(2, 4)
        i = rng.randrange(1, len(text) - width)
        return text[:i] + text[i + width :], ["word-drop"]

    def _mangle_numbers(self, text: str, rng: random.Random) -> Tuple[str, List[str]]:
        """Perturb a digit or a unit -- the 「数字・単位の誤り」 class.

        Claim: SUPPORT -- numbers are the errors that survive proofreading and
        cost money, so they get their own labelled class.
        """
        if rng.random() >= self.config.number_error_rate:
            return text, []
        idx = [i for i, ch in enumerate(text) if ch in _DIGITS]
        if idx:
            i = idx[rng.randrange(len(idx))]
            pool = [c for c in "0123456789" if c != text[i]]
            return text[:i] + pool[rng.randrange(len(pool))] + text[i + 1 :], ["number-unit"]
        for unit in _UNITS:
            if unit in text:
                other = [u for u in _UNITS if u != unit]
                return text.replace(unit, other[rng.randrange(len(other))], 1), ["number-unit"]
        return text, []

    def _hallucinate(self, text: str, rng: random.Random) -> Tuple[str, List[str]]:
        """Append a canned hallucination, as Whisper does at a silent tail.

        Claim: SUPPORT -- pathology class 「定型の幻聴」, scored by metric (5).
        """
        if rng.random() >= self.config.hallucination_rate or not self.hallucination_patterns:
            return text, []
        pat = self.hallucination_patterns[rng.randrange(len(self.hallucination_patterns))]
        sep = "" if text.endswith(("。", "、", "！", "？")) else "。"
        return f"{text}{sep}{pat}。", ["hallucination"]

    # ------------------------------------------------------------------- batch
    def make_pairs(
        self,
        sentences: Sequence[str],
        glossary: Glossary,
        split: str = "train",
        speaker: str = "sim",
        asr_model: str = "simulated",
        source_corpus: str = "synthetic",
        source_license: str = "CC0-1.0",
        id_prefix: str = "sim",
    ) -> List[ErrorPair]:
        """Turn a list of gold sentences into labelled :class:`ErrorPair` records.

        Claim: SUPPORT.
        """
        entries = list(glossary)
        out: List[ErrorPair] = []
        for i, gold in enumerate(sentences):
            key = f"{id_prefix}-{split}-{i}"
            hyp, terms, labels = self.corrupt(gold, entries, key=key)
            out.append(
                ErrorPair(
                    id=key,
                    gold=gold,
                    hypothesis=hyp,
                    glossary_terms=terms,
                    error_types=labels,
                    speaker=speaker,
                    asr_model=asr_model,
                    source_corpus=source_corpus,
                    source_license=source_license,
                    split=split,
                    provenance="simulated",
                )
            )
        return out
